name:                XMonad

dependencies:
- base >= 4.7 && < 5
- xmonad
- xmonad-contrib
- X11
- containers
- directory

library:
  source-dirs: src/lib

executables:

  xmonad:
    source-dirs: src/lib
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - XMonad
  xmobar:
    source-dirs: src
    main:                xmobar.hs       
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wno-missing-signatures
    - -with-rtsopts=-N
    dependencies:
    - xmobar

      #  xmonadctl:
      #source-dirs: src
      #main:                xmonadctl.hs       
      #ghc-options:
      #- -Wall
      #- -Wextra
      #- -Werror
   
      #xmonadpropwrite:
      # source-dirs: src
      #main:                xmonadpropwrite.hs       
      #dependencies:
      #- bytestring

      #xmonadpropread:
      #source-dirs: src
      #main:                xmonadpropread.hs       
      #ghc-options:
      #- -Wall
      #- -Wextra
      #- -Werror
      #dependencies:
      #- utf8-string


